EmailConfig:
  user: robot_remind@qq.com
  pwd: ztdzxbefwbasbcdh
  host: smtp.qq.com
  port: 465
  to_user:
    - peng.nengpeng@ricequant.com
    - pnp652065211@dingtalk.com
  subject: APP自动化执行完成
  report_path: report/report.html
  file_name: APP自动化测试报告.html

DingdingConfig:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=a3a6486d8f4bf1e7e3b2ff17a1c06c49ce1075d75e94a577c8eefc3147dcabcb
  secret: SEC8eb61cfc6d7df28626fb870aaaddfcdb87020b933dcaad541e956ef4644677c0

WeChatConfig:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d2151a5b-c834-4bd4-bcae-3570b85f4d2b

# python -m http.server 8001 -b 192.168.10.210
ReportUrl: http://192.168.10.210:8001/app_auto_test/report/report.html

MysqlConfig:
  host: 127.0.0.1
  user: root
  pwd: 123456
  port: 3306

Environment:
  server: http://127.0.0.1:4723/wd/hub
  platformName: null
  deviceName: SM_G988N
  noReset: False
  newCommandTimeout: 30
  automationName: UiAutomator2
  unicodeKeyboard: False
  resetKeyboard: False
  chromedriverExecutable: None
  heard:
    appPackage: com.xa.heard
    appActivity: .ui.channel.activity.WelcomeV2Activity


ReportTemplate: >
  本次APP自动化测试结果如下（详情请查看邮箱附件）：
    用例总数：{}
    用例Passed：{}
    用例Failed：{}
    用例Error：{}
    用例Skpit：{}
    用例通过率：{}%
    执行时长：{}s